Locator/Locator/urls.py
from django.contrib import admin
from django.contrib.auth import urls
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('', include('frontend.urls')),
    path('', include('reviews.urls')),
    path('', include('posting_service.urls')),
    path('', include('booking.urls')),
    path('', include(urls))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Locator/booking/urls.py
from django.urls import path
from .views import bookAppointment, EditAppointmentView, CancelAppointmentView, ManageAppointmentView

app_name = 'appointments'

urlpatterns = [
    path('book/<str:service_id>/', bookAppointment, name="book"),
    path('appointments/', ManageAppointmentView, name="manage_appointments"),
    path('appointment/<str:appointment_id>/edit/', EditAppointmentView, name="edit_appointment"),
    path('appointment/<str:appointment_id>/cancel/', CancelAppointmentView, name="cancel_appointment"),
]

Locator/login/urls.py
from django.urls import path
from .views import register

urlpatterns = [
    path('register/', register, name="register"),
]

Locator/booking/models.py
from django.db import models
from django.contrib.auth.models import User
from posting_service.models import Service
from django.utils import timezone
import string
import random

def generate_unique_code():
    length = 6

    while True:
        AppointmentID = ''.join(random.choices(string.ascii_uppercase, k=length))
        if Appointment.objects.filter(AppointmentID=AppointmentID).count() == 0:
            break

    return AppointmentID

# Create your models here.
class Appointment(models.Model):
  AppointmentID = models.CharField(max_length=8, default=generate_unique_code, unique=True)
  client = models.ForeignKey(User, on_delete=models.CASCADE)
  service = models.ForeignKey(Service, on_delete=models.CASCADE)
  status = models.CharField(max_length=10, choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], blank=True)
  date_time = models.DateTimeField(default=timezone.now)
  created_at = models.DateTimeField(auto_now_add=True, null=True)

Locator/booking/forms.py
from django import forms
from .models import Appointment

class AppointmentForm(forms.ModelForm):
  class Meta:
    model = Appointment
    fields = ['date_time', "status"]
    widgets = {
      'date_time': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
    }

Locator/booking/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Appointment
from posting_service.models import Service
from .forms import AppointmentForm
from django.contrib.auth.decorators import login_required
from .models import Appointment


# Create your views here.
@login_required
def bookAppointment(request, service_id):
  service = Service.objects.get(ServiceID=service_id)
  if request.method == 'POST':
    form = AppointmentForm(request.POST)
    if form.is_valid():
      appointment = form.save(commit=False)
      appointment.client = request.user
      appointment.service = service
      appointment.status = 'PENDING'
      appointment.save()
      return redirect('/appointments')
  else:
    form = AppointmentForm()
  return render(request, 'appointment.html', {'form': form, 'service': service})

def EditAppointmentView(request, appointment_id):
  appointment = Appointment.objects.get(AppointmentID=appointment_id)
  if request.method == "POST":
    form = AppointmentForm(request.POST, instance=appointment)
    if form.is_valid():
      form.save()
      return redirect('/appointments')
  else:
    form = AppointmentForm(instance=appointment)
    
  return render(request, 'edit_appointment.html', {'form' : form, 'appointment':appointment})

def CancelAppointmentView(request, appointment_id):
  appointment = Appointment.objects.get(AppointmentID=appointment_id)
  appointment.delete()
  return redirect('/appointments')

@login_required
def ManageAppointmentView(request):
  appointments = Appointment.objects.filter(client=request.user).order_by('date_time')
  return render(request, 'manage_appointments.html', {'appointments': appointments})
  

Locator/booking/templates/appointment.html
{% extends "base.html" %}
{% load static %}

  {% block content %}
    <h2 style="margin-left: 50%; transform: translate(-50%); margin-bottom: 30px;">Book an Appointment for <i>{{ service.serviceName }}</i></h2>
    <form method="post" style="margin-left: 50%; transform: translate(-50%);">
      <div style="margin-left: 50%; transform: translate(-50%);">
        {% csrf_token %}
        {{ form.date_time }}
        <button type="submit" class="btn custom-button">Book Appointment</button>
      </div>
    </form>
  {% endblock %}

Locator/booking/templates/edit_appointment.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <h2 style="text-align: center; margin-bottom: 30px;">Edit Appointment for <i>{{ appointment.service.serviceName }}</i></h2>
  <form method="post" style="margin-left: 50%; transform: translate(-50%);">
    <div style="margin-left: 50%; transform: translate(-50%);">
      {% csrf_token %}
      {{ form.date_time }}
      <button type="submit" class="btn custom-button">Book Appointment</button>
      <a href="{% url 'home' %}" class="btn btn-secondary">Cancel</a>
    </div>
  </form>
  
{% endblock content %}

Locator/booking/templates/manage_appointments.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  {% if appointments %}
    <div class="row row-cols-md-3" style="width: 80%; margin-left: 50%; transform: translate(-50%);">
      {% for appointment in appointments %}
        <div class="col mb-4">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">Appointment for {{appointment.service.serviceName}}</h5>
              <p class="card-text">Scheduled for: {{ appointment.date_time }}</p>
              <p class="card-text">Status: {{ appointment.status }}</p>
              <div>
                <a href="{% url 'appointments:edit_appointment' appointment.AppointmentID %}" class="btn btn-primary">Edit</a>
                <button type="button" class="btn btn-danger delete-now" data-toggle="modal" data-target="#staticBackdrop" data-service-name="{{ appointment.service.serviceName }}" data-appointment-id="{{ appointment.AppointmentID }}">Cancel Appointment</button>
              </div>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  {% else %}
    <div class="alert alert-info" role="alert" style="width: 75%; margin-left: 50%; transform: translate(-50%);">
      You have no scheduled appointments. Click <a href="{% url 'explore' %}">here</a> to explore all services.
    </div>
  {% endif %}

  <div class="modal fade" id="staticBackdrop" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="staticBackdropLabel">Cancel Appointment for <span id="service-name"></span>?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          Are you sure you want to cancel your appointment? You will lose your time slot!
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="button" class="btn btn-danger" id="confirm-delete" data-service-id="">Confirm</button>
        </div>
      </div>
    </div>
  </div>
  <a type="button" class="btn btn-secondary" href="{% url 'home' %}" style="margin-left: 30px;">
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-caret-left" viewBox="0 0 16 16">
    <path d="M10 12.796V3.204L4.519 8zm-.659.753-5.48-4.796a1 1 0 0 1 0-1.506l5.48-4.796A1 1 0 0 1 11 3.204v9.592a1 1 0 0 1-1.659.753"></path></svg>
    Home
  </a>

  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script>
    $(document).ready(function() {
      // Function to set the service name in the modal title
      $('.delete-now').click(function() {
        var serviceName = $(this).data('service-name');
        var appointmentID = $(this).data('appointment-id')
        $('#service-name').text(serviceName);
        $('#confirm-delete').data('appointment-id', appointmentID);
      });
    });
    $('#confirm-delete').click(function() {
      var appointmentID = $(this).data('appointment-id');
      // Construct the delete URL using the service ID
      var deleteUrl = `{% url 'appointments:cancel_appointment' 'dummyId' %}`.replace('dummyId', appointmentID);
      // Redirect to the delete URL
      window.location.href = deleteUrl;
    });
  </script>
{% endblock content %}