Locator/Locator/urls.py
from django.contrib import admin
from django.contrib.auth import urls
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('', include('frontend.urls')),
    path('', include('reviews.urls')),
    path('', include('posting_service.urls')),
    path('', include('booking.urls')),
    path('', include(urls))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Locator/booking/urls.py
from django.urls import path
from .views import bookAppointment, EditAppointmentView, CancelAppointmentView, ManageAppointmentView

app_name = 'appointments'

urlpatterns = [
    path('book/<str:service_id>/', bookAppointment, name="book"),
    path('appointments/', ManageAppointmentView, name="manage_appointments"),
    path('appointment/<str:appointment_id>/edit/', EditAppointmentView, name="edit_appointment"),
    path('appointment/<str:appointment_id>/cancel/', CancelAppointmentView, name="cancel_appointment"),
]

Locator/login/urls.py
from django.urls import path
from .views import register

urlpatterns = [
    path('register/', register, name="register"),
]

Locator/posting_service/urls.py
from django.urls import path
from .views import ServiceCreateView, UpdateServiceView, DeleteServiceView, ManageServicesView, ServicePageView, ServiceAppointmentsView, ChangeStatus, ServiceCategoryView

app_name='posting_service'

urlpatterns = [
    path('create-service/', ServiceCreateView, name="create-service"),
    path('services/', ManageServicesView, name="manage_services"),
    path('service/<str:service_id>/edit/', UpdateServiceView, name="edit_service"),
    path('service/<str:service_id>/delete/', DeleteServiceView, name='delete_service'),
    path('serviceview/<str:service_id>/', ServicePageView, name="service_page"),
    path('serviceapp/<str:service_id>/', ServiceAppointmentsView, name="service_appointments"),
    path('appointmentstatus/<str:appointment_id>/', ChangeStatus, name="change_status"),
    path('category/<str:category>/', ServiceCategoryView, name="category"),
]

Locator/posting_service/models.py
from django.db import models
from django.contrib.auth.models import User
import string
import random


def generate_unique_code():
    length = 6

    while True:
        ServiceID = ''.join(random.choices(string.ascii_uppercase, k=length))
        if Service.objects.filter(ServiceID=ServiceID).count() == 0:
            break

    return ServiceID

def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return f'user_{instance.User.username}/{filename}'
  
# Create your models here.
class Service(models.Model):
  ServiceID = models.CharField(max_length=8, default=generate_unique_code, unique=True)
  freelancer = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
  serviceName = models.CharField(max_length=250)
  description = models.TextField()
  price = models.DecimalField(max_digits=10, decimal_places=2) 
  credentials = models.FileField(upload_to='documents/', null=True, blank=True)
  category = models.CharField(max_length=40, choices=[('EDUCATION', 'Education'), ('PERSONAL CARE AND GROOMING', 'Personal Care and Grooming'), ('CLEANING AND JANITORIAL', 'Cleaning and Janitorial'), ('CONSTRUCTION AND RENOVATION', 'Construction and Renovation'), ('LANDSCAPING AND GARDENING', 'Landscaping and Gardening'), ('CHILD AND PET CARE', 'Child and Pet Care'), ('TECHNOLOGY AND CREATIVE ARTS', 'Technology and Creative Arts'), ('OTHER', 'Other')], null=True, blank=True)
  created_at = models.DateTimeField(auto_now_add=True)
  
class Photo(models.Model):
    service = models.ForeignKey(Service, on_delete=models.CASCADE, null=True, blank=True)
    service_img = models.ImageField(upload_to='images/', null=True, blank=True)
    
      

Locator/posting_service/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Service


class ServiceForm(forms.ModelForm):
  class Meta:
    model = Service
    fields = ["id", "serviceName", "description", 'category', "price", "credentials"]

Locator/posting_service/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .forms import ServiceForm
from .models import Service, Photo
from reviews.models import Review
from booking.models import Appointment
from reviews.forms import ReviewForm
from booking.forms import AppointmentForm
from django.db.models import Avg


# Create your views here.

def ServiceCreateView(request):
  if request.method == 'POST':
    form = ServiceForm(request.POST, request.FILES) 
    images = request.FILES.getlist('images')
    if form.is_valid():
      service = form.save(commit=False)
      service.freelancer = request.user
      service.save()
      for image in images:
        photo = Photo.objects.create(service=service, service_img=image)
      return redirect('/services')
  else:
    form = ServiceForm()
  return render(request, 'service.html', {'form' : form})

def UpdateServiceView(request, service_id):
  service = Service.objects.get(ServiceID=service_id)
  if request.method == "POST":
    form = ServiceForm(request.POST, request.FILES, instance=service)
    if form.is_valid():
      form.save()
      return redirect('/services')
  else:
    form = ServiceForm(instance=service)
    
  return render(request, 'edit_service.html', {'form' : form})

def DeleteServiceView(request, service_id):
  service = Service.objects.get(ServiceID=service_id)
  service.delete()
  return redirect('/services')

def ServicePageView(request, service_id):
  service = Service.objects.get(ServiceID=service_id)
  reviews = Review.objects.filter(service=service)
  photos = Photo.objects.filter(service=service)
  average_rating = reviews.aggregate(Avg('rating'))['rating__avg'] or 0
  average_rating_rounded = round(average_rating, 2)
  if request.method == "POST":
    form = ReviewForm(request.POST)
    if form.is_valid():
      review = form.save(commit=False)
      review.client = request.user
      review.service = service
      review.rating = form.cleaned_data['rating']
      review.comment = form.cleaned_data['comment']
      review.save()
      return redirect('/serviceview/' + service_id)
  else:
    form = ReviewForm()
  
  return render(request, 'service_page.html', {'form' : form, 'service' : service, 'reviews' : reviews, 'photos':photos,'average_rating': average_rating_rounded})

def ServiceAppointmentsView(request, service_id):
  service = Service.objects.get(ServiceID=service_id)
  appointments = Appointment.objects.filter(service=service)
  return render(request, 'manage_app.html', {'appointments':appointments})

def ChangeStatus(request, appointment_id):
  appointment = Appointment.objects.get(AppointmentID=appointment_id)
  if request.method == "POST":
    form = AppointmentForm(request.POST, instance=appointment)
    if form.is_valid():
      form.save()
      return redirect('/services')
  else:
    form = AppointmentForm(instance=appointment)
    
  return render(request, "status.html", {"form" : form})
  
def ServiceCategoryView(request, category):
  services = Service.objects.filter(category=category)
  return render(request, 'category.html', {'services':services, 'category':category})

@login_required
def ManageServicesView(request):
    services = Service.objects.filter(freelancer=request.user).order_by('created_at')
    return render(request, 'manage_services.html', {'services': services})
  
  
  

Locator/posting_service/templates/category.html
{% extends "base.html" %}
{% load static %}
{% load custom_filters %}

{% block content %}
  <h5 style="text-align:center; margin-bottom: 30px;">Services for {{ category }}</h5>
  {% for service in services %}
    <div id="review" style="margin-left: 50%; transform: translate(-50%);">
      <div id="leftsection">
          <div id="ptitle" style="margin-top: 10px"> {{ service.serviceName }} </div>
          <div id="pdescription">
              {{ service.description | truncate_with_ellipsis:350 }}
          </div>
          <div id="puser">
            <div id="pusername">
                {{ service.freelancer.first_name }} {{ service.freelancer.last_name }}
            </div>
          </div>
          <div id="other">
              <div class="heartsection">
                  <i class="far fa-heart animated-heart-outline fa-2x"></i>
                  <i class="fas fa-heart animated-heart fa-2x"></i>
              </div>
              <a href="{% url 'posting_service:service_page' service.ServiceID %}" class="btn custom-button" style="height: 40px; margin-left: 15px;">View</a>
              {% comment %} <div class="starsection">
                  <i class="far fa-star starOutline" data-star="1"></i>
                  <i class="far fa-star starOutline" data-star="2"></i>
                  <i class="far fa-star starOutline" data-star="3"></i>
                  <i class="far fa-star starOutline" data-star="4"></i>
                  <i class="far fa-star starOutline" data-star="5"></i>
              </div> {% endcomment %}
          </div>
      </div>
      <div id="rightsection">
          <div id="imagesection">
              {% if service.photo_set.first %}
                <img src="{{ service.photo_set.first.service_img.url }}" style="width: 100%;height: 100%; object-fit: cover;">
              {% else %}
                {% if service.category == 'EDUCATION' %}
                  <img src="{% static 'img/education.jpeg' %}" style="width: 100%;height: 100%; object-fit: cover;">
                {% elif service.category == 'PERSONAL CARE AND GROOMING' %}
                  <img src="{% static 'img/personal_care_and_grooming.jpeg' %}" style="width: 100%;height: 100%; object-fit: cover;">
                {% elif service.category == 'CLEANING AND JANITORIAL' %}
                  <img src="{% static 'img/cleaning_and_janitorial.jpeg' %}" style="width: 100%;height: 100%; object-fit: cover;">
                {% elif service.category == 'CONSTRUCTION AND RENOVATION' %}
                  <img src="{% static 'img/construction.jpeg' %}" style="width: 100%;height: 100%; object-fit: cover;">
                {% elif service.category == 'LANDSCAPING AND GARDENING' %}
                  <img src="{% static 'img/gardening.avif' %}" style="width: 100%;height: 100%; object-fit: cover;">
                {% elif service.category == 'CHILD AND PET CARE' %}
                  <img src="{% static 'img/child_care.jpeg' %}" style="width: 100%;height: 100%; object-fit: cover;">
                {% elif service.category == 'TECHNOLOGY AND CREATIVE ARTS' %}
                  <img src="{% static 'img/film.jpeg' %}" style="width: 100%;height: 100%; object-fit: cover;">
                {% else %}
                  <img src="{% static 'img/freelancer.png' %}" style="width: 100%;height: 100%; object-fit: cover;">
                {% endif %}
                  
              {% endif %}
              
          </div>
      </div>
      <div id="price-section">
        ${{ service.price }}/hr
      </div>
    </div>
  {% endfor %}
  
{% endblock content %}

Locator/posting_service/templates/edit_service.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <div class="sign-up-container" style="margin-left: 50%; transform: translate(-50%); text-align: center;">
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="form-group">
        <label>Service Title</label>
        <div>{{ form.serviceName }}</div>
      </div>
      <div class="form-group">
        <label>Description</label>
        <div>{{ form.description }}</div>
      </div>
      <div class="form-group">
        <label>Price</label>
        <div>{{ form.price }}</div>
      </div>
      <div class="form-group">
        <label>Category</label>
        <div>{{ form.category }}</div>
      </div>
      <div class="form-group">
        <label>Upload image</label>
        <input required name="images" type="file" multiple class="form-control-file" accept="image/*" style="margin-left:50%; transform: translate(-15%);">
      </div>
      <div class="form-group">
        <label>Credentials</label>
        <div style="margin-left:50%; transform: translate(-37%);">{{ form.credentials }}</div>
      </div>
      <button type="submit" class="btn custom-button">Submit</button>
      <a href="{% url 'home' %}" class="btn btn-secondary">Cancel</a>
    </form>
  </div>
  
{% endblock %}

Locator/posting_service/templates/manage_app.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  {% if appointments %}
    <div class="row row-cols-md-3" style="width: 80%; margin-left: 50%; transform: translate(-50%);">
      {% for appointment in appointments %}
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">{{ appointment.client.first_name }} {{ appointment.client.last_name }}</h5>
                <p class="card-text">{{ appointment.date_time|date:"D, N d - g:i A" }}</p>
                <p class="card-text">Status: {{ appointment.status }}</p>
                <a href="{% url 'posting_service:change_status' appointment.AppointmentID %}" class="btn btn-primary">Change Status</a>
            </div>
        </div>
      {% endfor %}
    </div>
  {% else %}
    <div class="alert alert-info" role="alert" style="width: 75%; margin-left: 50%; transform: translate(-50%);">
      There are no appointments scheduled.
    </div>
  {% endif %}
    <a type="button" class="btn btn-secondary" href="{% url 'home' %}" style="margin-left: 30px;">
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-caret-left" viewBox="0 0 16 16">
      <path d="M10 12.796V3.204L4.519 8zm-.659.753-5.48-4.796a1 1 0 0 1 0-1.506l5.48-4.796A1 1 0 0 1 11 3.204v9.592a1 1 0 0 1-1.659.753"></path></svg>
      Home
  </a>
{% endblock content %}

Locator/posting_service/templates/manage_services.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  {% if services %}
      {% for service in services %}
        <div class="card w-75" style="margin-left: 50%; transform: translate(-50%);">
          <div class="card-body">
            <h5 class="card-title">{{ service.serviceName }}</h5>
            <p class="card-text">{{ service.description }}</p>
            <p class="card-text">${{ service.price }}/hr</p>
            <div>
                <a href="{% url 'posting_service:service_appointments' service.ServiceID %}" class="btn btn-secondary">Manage Appointments</a>
                <a href="{% url 'posting_service:edit_service' service.ServiceID %}" class="btn btn-primary">Edit</a>
                <button type="button" class="btn btn-danger delete-now" data-toggle="modal" data-target="#staticBackdrop" data-service-name="{{ service.serviceName }}" data-service-id="{{ service.ServiceID }}">Delete</button>
            </div>
          </div>
        </div>
        <div style="margin-bottom: 30px;"></div>
      {% endfor %}
  {% else %}
    <div class="alert alert-info" role="alert" style="width: 75%; margin-left: 50%; transform: translate(-50%);">
      There are no services available. Click <a href="{% url 'posting_service:create-service' %}">here</a> to create a service posting.
    </div>
  {% endif %}

  <!-- Modal -->
  <div class="modal fade" id="staticBackdrop" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="staticBackdropLabel">Delete <span id="service-name"></span>?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          Are you sure you want to delete this service? This action cannot be reversed!
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="button" class="btn btn-danger" id="confirm-delete" data-service-id="">Confirm</button>
        </div>
      </div>
    </div>
  </div>

  <a type="button" class="btn btn-secondary" href="{% url 'home' %}" style="margin-left: 30px;">
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-caret-left" viewBox="0 0 16 16">
    <path d="M10 12.796V3.204L4.519 8zm-.659.753-5.48-4.796a1 1 0 0 1 0-1.506l5.48-4.796A1 1 0 0 1 11 3.204v9.592a1 1 0 0 1-1.659.753"></path></svg>
    Home
  </a>

  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script>
    $(document).ready(function() {
      // Function to set the service name in the modal title
      $('.delete-now').click(function() {
        var serviceName = $(this).data('service-name');
        var serviceID = $(this).data('service-id')
        $('#service-name').text(serviceName);
        $('#confirm-delete').data('service-id', serviceID);
      });
    });
    $('#confirm-delete').click(function() {
      var serviceID = $(this).data('service-id');
      // Construct the delete URL using the service ID
      var deleteUrl = `{% url 'posting_service:delete_service' 'dummyId' %}`.replace('dummyId', serviceID);
      // Redirect to the delete URL
      window.location.href = deleteUrl;
    });
  </script>
{% endblock content %}

Locator/posting_service/templates/service.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <div class="sign-up-container" style="margin-left: 50%; transform: translate(-50%); text-align: center;">
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="form-group">
        <label>Service Title</label>
        <div>{{ form.serviceName }}</div>
      </div>
      <div class="form-group">
        <label>Description</label>
        <div>{{ form.description }}</div>
      </div>
      <div class="form-group">
        <label>Price</label>
        <div>{{ form.price }}</div>
      </div>
      <div class="form-group">
        <label>Category</label>
        <div>{{ form.category }}</div>
      </div>
      <div class="form-group">
        <label>Upload image</label>
        <input required name="images" type="file" multiple class="form-control-file" accept="image/*" style="margin-left:50%; transform: translate(-15%);">
      </div>
      <div class="form-group">
        <label>Credentials</label>
        <div style="margin-left:50%; transform: translate(-37%);">{{ form.credentials }}</div>
      </div>
      <button type="submit" class="btn custom-button">Submit</button>
    </form>
  </div>
{% endblock %}

Locator/posting_service/templates/service_page.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <div class="card" style="width: 70%; margin-left: 50%; transform: translate(-50%);">
    {% if photos %}
      <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
          {% for photo in photos %}
            <div class="carousel-item {% if forloop.first %}active{% endif %}">
              <img src="{{ photo.service_img.url }}" class="d-block w-100" style="height:600px; object-fit: cover;">
            </div>
          {% endfor %}
        </div>
        <button class="carousel-control-prev" type="button" data-target="#carouselExampleControls" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-target="#carouselExampleControls" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </button>
      </div>
    {% else %}
      <img src="{% static "img/IMG2.jpg" %}" class="card-img-top" style="height:600px; object-fit: cover;">
    {% endif %}
    
    <div class="card-body">
      <h5 class="card-title"> {{ service.serviceName }}
        {% if average_rating != 0 %}
          <small class="text-muted" style="margin-left:15px;">{{ average_rating }}/5</small>
        {% endif %}</h5>
      <p class="card-text">{{ service.description }}</p>
      <p class="card-text">${{ service.price }}/hr</p>
      {% if service.credentials %}
        <a href="{{ service.credentials.url }}" class="btn btn-secondary" download>View Credentials</a>
      {% endif %}
      <a href="{% url 'appointments:book' service.ServiceID %}" class="btn custom-button">Book Now</a>
      <p class="card-text"><small class="text-muted">Posted on {{service.created_at|date:"N d"}}</small></p>
    </div>
  </div>

  <div style="margin-bottom: 100px;"></div>

  {% comment %} <h2>Review for {{ service.serviceName }}</h2> {% endcomment %}
  {% if user.is_authenticated %}
    <form method="post" style="width: 50%; margin-left: 50%; transform: translate(-50%);">
      {% csrf_token %}
      {% comment %} {{ form.rating }} {% endcomment %}
      <div class="form-group">
        <label for="ratingform">Rating</label>
        <select class="form-control" id="ratingform" name="rating">
          <option value="1">1</option>
          <option value="2">2</option>
          <option value="3">3</option>
          <option value="4">4</option>
          <option value="5">5</option>
        </select>
        <label for="exampleFormControlTextarea1">Comment</label>
        <textarea class="form-control" id="exampleFormControlTextarea1" name="comment" rows="3"></textarea>
      </div>
      <button type="submit" class="btn custom-button">Submit</button>
    </form>
  {% endif %}
  
  <div class="reviews-container" style="margin-top: 30px;">
    {% for review in reviews %}
      <div class="review">
        <div class="user-info">
          <div class="user-details">
            <div class="user-name">{{ review.client.first_name }} {{ review.client.last_name }}</div>
            <div class="review-date">{{review.created_at|date:"N d, Y"}}</div>
          </div>
        </div>
        <div class="review-content">
          <p>{{ review.comment }}</p>
        </div>
        <p> {{ review.rating }}<small class="text-muted">/5</small></p>
      </div>
    {% endfor %}
  </div>
{% endblock content %}

Locator/posting_service/templates/status.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<form method="post" style="margin-left: 50%; transform: translate(-50%);">
  <div style="margin-left: 50%; transform: translate(-50%);">
    {% csrf_token %}
    {{ form.date_time }}
    {{ form.status }}
    <button type="submit" class="btn custom-button">Change Status</button>
  </div>
</form>
<a href="{% url 'home' %}" class="btn btn-secondary" style="margin-left: 50px;">Cancel</a>
{% endblock content %}