Locator/Locator/urls.py
from django.contrib import admin
from django.contrib.auth import urls
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('', include('frontend.urls')),
    path('', include('reviews.urls')),
    path('', include('posting_service.urls')),
    path('', include('booking.urls')),
    path('', include(urls))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Locator/booking/urls.py
from django.urls import path
from .views import bookAppointment, EditAppointmentView, CancelAppointmentView, ManageAppointmentView

app_name = 'appointments'

urlpatterns = [
    path('book/<str:service_id>/', bookAppointment, name="book"),
    path('appointments/', ManageAppointmentView, name="manage_appointments"),
    path('appointment/<str:appointment_id>/edit/', EditAppointmentView, name="edit_appointment"),
    path('appointment/<str:appointment_id>/cancel/', CancelAppointmentView, name="cancel_appointment"),
]

Locator/frontend/urls.py
from django.urls import path, include
from .views import home, ViewServices

urlpatterns = [
    path('', home, name="home"),
    path('explore/', ViewServices, name="explore")
]

Locator/login/urls.py
from django.urls import path
from .views import register

urlpatterns = [
    path('register/', register, name="register"),
]

Locator/posting_service/urls.py
from django.urls import path
from .views import ServiceCreateView, UpdateServiceView, DeleteServiceView, ManageServicesView, ServicePageView, ServiceAppointmentsView, ChangeStatus, ServiceCategoryView

app_name='posting_service'

urlpatterns = [
    path('create-service/', ServiceCreateView, name="create-service"),
    path('services/', ManageServicesView, name="manage_services"),
    path('service/<str:service_id>/edit/', UpdateServiceView, name="edit_service"),
    path('service/<str:service_id>/delete/', DeleteServiceView, name='delete_service'),
    path('serviceview/<str:service_id>/', ServicePageView, name="service_page"),
    path('serviceapp/<str:service_id>/', ServiceAppointmentsView, name="service_appointments"),
    path('appointmentstatus/<str:appointment_id>/', ChangeStatus, name="change_status"),
    path('category/<str:category>/', ServiceCategoryView, name="category"),
]

Locator/frontend/models.py
from django.db import models

# Create your models here.

Locator/posting_service/models.py
from django.db import models
from django.contrib.auth.models import User
import string
import random


def generate_unique_code():
    length = 6

    while True:
        ServiceID = ''.join(random.choices(string.ascii_uppercase, k=length))
        if Service.objects.filter(ServiceID=ServiceID).count() == 0:
            break

    return ServiceID

def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return f'user_{instance.User.username}/{filename}'
  
# Create your models here.
class Service(models.Model):
  ServiceID = models.CharField(max_length=8, default=generate_unique_code, unique=True)
  freelancer = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
  serviceName = models.CharField(max_length=250)
  description = models.TextField()
  price = models.DecimalField(max_digits=10, decimal_places=2) 
  credentials = models.FileField(upload_to='documents/', null=True, blank=True)
  category = models.CharField(max_length=40, choices=[('EDUCATION', 'Education'), ('PERSONAL CARE AND GROOMING', 'Personal Care and Grooming'), ('CLEANING AND JANITORIAL', 'Cleaning and Janitorial'), ('CONSTRUCTION AND RENOVATION', 'Construction and Renovation'), ('LANDSCAPING AND GARDENING', 'Landscaping and Gardening'), ('CHILD AND PET CARE', 'Child and Pet Care'), ('TECHNOLOGY AND CREATIVE ARTS', 'Technology and Creative Arts'), ('OTHER', 'Other')], null=True, blank=True)
  created_at = models.DateTimeField(auto_now_add=True)
  
class Photo(models.Model):
    service = models.ForeignKey(Service, on_delete=models.CASCADE, null=True, blank=True)
    service_img = models.ImageField(upload_to='images/', null=True, blank=True)
    
      

Locator/frontend/views.py
from django.shortcuts import render
from posting_service.models import Service

# Create your views here.
def ViewServices(request):
  services = Service.objects.all()
  return render(request, 'explore.html', {'services': services})

def home(response):
  return render(response, "test.html")

Locator/frontend/templates/base.html
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width,initial-scale=1.0">
        <title>Locator</title>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

        <link rel="stylesheet" href="{% static 'css/home.css' %}">
        <link rel="stylesheet" href="{% static 'css/proposal.css' %}">
        <link rel="stylesheet" href="{% static 'css/categories.css' %}">
        <link rel="stylesheet" href="{% static 'css/explore.css' %}">
        <link rel="stylesheet" href="{% static 'css/review.css' %}">
        <link rel="stylesheet" href="{% static 'css/appointment.css' %}">

        <script src="functions.js"></script>  
    </head>
    <body>
        <header class="header">
            <a href="{% url 'home' %}" class="logo" id="header-item">Locator</a>
            <nav class="navbar">
                <a href="{% url 'home' %}" id="header-item">Home</a>
                <a href="{% url 'explore' %}" id="header-item">Explore</a>
                {% comment %} <a href="#">Reviews</a> {% endcomment %}
                {% if user.is_authenticated %}
                    <div class="dropdown" style="margin-left: 50px;">
                        <button class="btn btn-secondary dropdown-toggle" type="button" data-toggle="dropdown" aria-expanded="false">
                            Welcome, {{ user.first_name|default:"User" }}
                        </button>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" id="dditem" href="{% url "posting_service:create-service" %}">Post a Service</a>
                            <a class="dropdown-item" id="dditem" href="{% url "posting_service:manage_services" %}">Manage Services</a>
                            <a class="dropdown-item" id="dditem" href="{% url "appointments:manage_appointments" %}">View Appointments</a>
                            <a class="dropdown-item" id="dditem" href="{% url "logout" %}">Logout</a>
                        </div>
                    </div>
                {% else %}
                    <a href="{% url "login" %}">
                        <button class="login">Login</button>
                    </a>
                    <a href="{% url "register" %}">
                        <button class="signup">Sign up</button>
                    </a>
                {% endif %}
            </nav>
        </header>
        
        <main style="margin-top:150px; margin-bottom:150px;">
            {% block content %}
            {% endblock content %} 
        </main>

        <footer id="footer">
            <div id="footersection">
          
              <div class="footer-column">
                <h4>About Us</h4>
                <ul>
                  <li><a href="#">Github</a></li>
                  <li><a href="#">UML</a></li>
                  <li><a href="#">Google Drive</a></li>
                  <li><a href="#">Slides</a></li>

                </ul>
              </div>
          
              <div class="footer-column">
                <h4>Categories</h4>
                <ul>
                  <li><a href="#">Link 1</a></li>
                  <li><a href="#">Link 2</a></li>
                  <li><a href="#">Link 3</a></li>
                  <li><a href="#">Link 4</a></li>
                </ul>
              </div>
          
              <div class="footer-column">
                <h4>Community</h4>
                <ul>
                  <li><a href="#">CS180</a></li>
                  <li><a href="#">Link 2</a></li>
                  <li><a href="#">Link 3</a></li>
                </ul>
              </div>
          
              <div class="footer-column">
                <h4>Languages</h4>
                <ul>
                  <li><a href="#">English</a></li>
                  <li><a href="#">Spanish</a></li>
                  <li><a href="#">French</a></li>
                  <li><a href="#">Dutch</a></li>
                </ul>
              </div>
          
            </div>
          </footer>
          <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
          <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
          <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
          <script src="{% static 'js/functions.js' %}"></script>
    </body>
</html>

Locator/frontend/templates/explore.html
{% extends "base.html" %}
{% load static %}
{% load custom_filters %}

{% block content %}
  {% for service in services %}
    <div id="review" style="margin-left: 50%; transform: translate(-50%);">
      <div id="leftsection">
          <div id="ptitle" style="margin-top: 10px; margin-bottom: 40px;"> {{ service.serviceName }} </div>
          <div id="pdescription">
              {{ service.description | truncate_with_ellipsis:350 }}
          </div>
          <div id="puser">
            <div id="pusername">
                {{ service.freelancer.first_name }} {{ service.freelancer.last_name }}
            </div>
          </div>
          <div id="other">
              <div class="heartsection">
                  <i class="far fa-heart animated-heart-outline fa-2x"></i>
                  <i class="fas fa-heart animated-heart fa-2x"></i>
              </div>
              <a href="{% url 'posting_service:service_page' service.ServiceID %}" class="btn custom-button" style="height: 40px; margin-left: 15px;">View</a>
          </div>
      </div>
      <div id="rightsection">
          <div id="imagesection">
              {% if service.photo_set.first %}
                <img src="{{ service.photo_set.first.service_img.url }}" style="width: 100%;height: 100%; object-fit: cover;">
              {% else %}
                {% if service.category == 'EDUCATION' %}
                  <img src="{% static 'img/education.jpeg' %}" style="width: 100%;height: 100%; object-fit: cover;">
                {% elif service.category == 'PERSONAL CARE AND GROOMING' %}
                  <img src="{% static 'img/personal_care_and_grooming.jpeg' %}" style="width: 100%;height: 100%; object-fit: cover;">
                {% elif service.category == 'CLEANING AND JANITORIAL' %}
                  <img src="{% static 'img/cleaning_and_janitorial.jpeg' %}" style="width: 100%;height: 100%; object-fit: cover;">
                {% elif service.category == 'CONSTRUCTION AND RENOVATION' %}
                  <img src="{% static 'img/construction.jpeg' %}" style="width: 100%;height: 100%; object-fit: cover;">
                {% elif service.category == 'LANDSCAPING AND GARDENING' %}
                  <img src="{% static 'img/gardening.avif' %}" style="width: 100%;height: 100%; object-fit: cover;">
                {% elif service.category == 'CHILD AND PET CARE' %}
                  <img src="{% static 'img/child_care.jpeg' %}" style="width: 100%;height: 100%; object-fit: cover;">
                {% elif service.category == 'TECHNOLOGY AND CREATIVE ARTS' %}
                  <img src="{% static 'img/film.jpeg' %}" style="width: 100%;height: 100%; object-fit: cover;">
                {% else %}
                  <img src="{% static 'img/freelancer.png' %}" style="width: 100%;height: 100%; object-fit: cover;">
                {% endif %}
              {% endif %}
              
          </div>
      </div>
      <div id="price-section">
        ${{ service.price }}/hr
      </div>
    </div>
  {% endfor %}
  
{% endblock content %}

Locator/frontend/templates/test.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div id="webpage">
        <p id="text">Where Talent Meets Opportunity</p>
        <div id="searchcontainer">
            <form action="" class="search-bar">
                <input type="text" placeholder="Search...">
                <button type="submit"><i class="fa fa-search fa-sm" style="color:white;"></i></button>
            </form>
        </div>
        <div class="slider">
            <div class="slide"></div>
            <div class="slide"></div>
            <div class="slide"></div>
            <div class="slide"></div>
            <div class="slide"></div>
        </div>
        <div class="circle" onclick="scrollToSection()">
            <i class="fa fa-angle-down fa-2x" style="color:white;"></i>
        </div>

        <div id="proposalsection">
            <div id="proposal">
                <div id="leftSection">
                    <img src="{% static 'img/purpose.jpeg' %}" alt="Proposal Image">
                </div>
                <div id="rightSection">
                <h2><i class="icon far fa-lightbulb"></i> Find a skill that best suits your needs</h2>
                <p><i class="icon far fa-money-bill-alt"></i> Low fees and no surprises - Know what you are paying for</p>
                <p><i class="icon fas fa-check"></i> Verified and Trustworthy - Meet people that can offer you quality services</p>
                <p><i class="icon fas fa-briefcase"></i> Build your career through us - Find exactly what you are looking for from the services we offer</p>
                <p><i class="icon fas fa-globe"></i> Issues? Talk to our support team - We are happy to help you with any problems you face</p>
                </div>
            </div>
        </div>
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="-100 0 1000 50" width="100%" height="50" preserveAspectRatio="none" style="display:block; width:100%;">
            <polygon points="-100,50 0,0 100,50" fill="var(--primary)" transform="rotate(180 0 25)"/>
            <polygon points="100,50 200,0 300,50" fill="var(--primary)" transform="rotate(180 200 25)"/>
            <polygon points="300,50 400,0 500,50" fill="var(--primary)" transform="rotate(180 400 25)"/>
            <polygon points="500,50 600,0 700,50" fill="var(--primary)" transform="rotate(180 600 25)"/>
            <polygon points="700,50 800,0 900,50" fill="var(--primary)" transform="rotate(180 800 25)"/>
        </svg>
        <div id="titlecategories">
            Categories
        </div>
        <div id = "categories">
            <a href="{% url 'posting_service:category' 'EDUCATION' %}"><div id="pannel">
                <img src="{% static 'img/education.jpeg' %}" alt="Description" style="width: 150%;height: 100%; object-fit:cover; object-position:right;"/>
                <span id="pannelheader" style="text-shadow:  -1px -1px 0 #000, 1px -1px 0 #000, -1px  1px 0 #000, 1px  1px 0 #000; ">
                    Education
                </span>
            </div></a>
            <a href="{% url 'posting_service:category' 'PERSONAL CARE AND GROOMING' %}"><div id="pannel">
                <img src="{% static 'img/personal_care_and_grooming.jpeg' %}" alt="Description" style="width: 150%;height: 100%; object-fit:cover; object-position:center;"/>
                <span id="pannelheader" style="font-size: 18px; text-shadow:  -1px -1px 0 #000, 1px -1px 0 #000, -1px  1px 0 #000, 1px  1px 0 #000; ">
                    Personal Care and Grooming
                </span>
            </div></a>
            <a href="{% url 'posting_service:category' 'CLEANING AND JANITORIAL' %}"><div id="pannel">
                <img src="{% static 'img/cleaning_and_janitorial.jpeg' %}" alt="Description" style="width: 150%;height: 100%; object-fit:cover; object-position:right;"/>
                <span id="pannelheader" style="font-size: 20px; text-shadow:  -1px -1px 0 #000, 1px -1px 0 #000, -1px  1px 0 #000, 1px  1px 0 #000; ">
                    Cleaning and Janitorial
                </span>
            </div></a> 
            <a href="{% url 'posting_service:category' 'CONSTRUCTION AND RENOVATION' %}"><div id="pannel">
                <img src="{% static 'img/construction.jpeg' %}" alt="Description" style="width: 150%;height: 100%; object-fit:cover; object-position:right;"/>
                <span id="pannelheader" style="font-size: 18px; text-shadow:  -1px -1px 0 #000, 1px -1px 0 #000, -1px  1px 0 #000, 1px  1px 0 #000; ">
                    Construction and Renovation
                </span>
            </div></a>
        </div>
        <div style="margin-bottom: 30px;"></div>
        <div id = "categories">
            <a href="{% url 'posting_service:category' 'LANDSCAPING AND GARDENING' %}"><div id="pannel">
                <img src="{% static 'img/gardening.avif' %}" alt="Description" style="width: 150%;height: 100%; object-fit:cover; object-position:right;"/>
                <span id="pannelheader" style="font-size: 18px; text-shadow:  -1px -1px 0 #000, 1px -1px 0 #000, -1px  1px 0 #000, 1px  1px 0 #000; ">
                    Landscaping and Gardening
                </span>
            </div></a>
            <a href="{% url 'posting_service:category' 'CHILD AND PET CARE' %}"><div id="pannel">
                <img src="{% static 'img/child_care.jpeg' %}" alt="Description" style="width: 150%;height: 100%; object-fit:cover; object-position:center;"/>
                <span id="pannelheader" style="font-size: 20px; text-shadow:  -1px -1px 0 #000, 1px -1px 0 #000, -1px  1px 0 #000, 1px  1px 0 #000; ">
                    Child and Pet Care
                </span>
            </div></a>
            <a href="{% url 'posting_service:category' 'TECHNOLOGY AND CREATIVE ARTS' %}"><div id="pannel">
                <img src="{% static 'img/film.jpeg' %}" alt="Description" style="width: 150%;height: 100%; object-fit:cover; object-position:right;"/>
                <span id="pannelheader" style="font-size: 18px; text-shadow:  -1px -1px 0 #000, 1px -1px 0 #000, -1px  1px 0 #000, 1px  1px 0 #000; ">
                    Technology and Creative Arts
                </span>
            </div></a>
            <a href="{% url 'posting_service:category' 'OTHER' %}"><div id="pannel">
                <img src="{% static 'img/freelancer.png' %}" alt="Description" style="width: 150%;height: 100%; object-fit:cover; object-position:right;"/>
                <span id="pannelheader" style="font-size: 20px; text-shadow:  -1px -1px 0 #000, 1px -1px 0 #000, -1px  1px 0 #000, 1px  1px 0 #000; ">
                    Other
                </span>
            </div></a>
        </div>
    </div>
{% endblock content %}

{% comment %} {% block content %}
    <div id="webpage" style="margin-top:-150px;">
        <div class="slider">
            <div id="text">
                Locator
                <form action="" class="search-bar">
                    <input type="text" placeholder="Search...">
                    <button type="submit"><i class="fa fa-search fa-sm" style="color:white;"></i></button>
                </form>
            </div>
            <div class="slide" style="background-image: url('{% static "img/IMG2.jpg" %}');"></div>
            <div class="slide" style="background-image: url('{% static "img/IMG3.jpg" %}');"></div>
            <div class="slide" style="background-image: url('{% static "img/IMG4.jpg" %}');"></div>
            <div class="slide" style="background-image: url('{% static "img/IMG5.jpg" %}');"></div>
            <div class="slide" style="background-image: url('{% static "img/IMG6.jpg" %}');"></div>
        </div>

        <div id="categories">
            <div class="pannel"><i class="fa fa-bell fa-3x"></i></div>
            <div class="pannel"><i class="fa fa-bath fa-3x"></i></div>
            <div class="pannel"><i class="fa fa-car fa-3x"></i></div>
            <div class="pannel"><i class="fa fa-bicycle fa-3x"></i></div>
        </div>
    </div>
{% endblock %} {% endcomment %}

    